-- MySQL Script generated by MySQL Workbench
-- Sun Jun  1 23:39:59 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema petshop
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema petshop
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `petshop` DEFAULT CHARACTER SET utf8 ;
USE `petshop` ;

-- -----------------------------------------------------
-- Table `petshop`.`Cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `petshop`.`Cliente` (
  `idCedula` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  `apellido` VARCHAR(45) NULL,
  `telefono` VARCHAR(15) NULL,
  `direccion` VARCHAR(45) NULL,
  `correoEletronico` VARCHAR(56) NULL,
  PRIMARY KEY (`idCedula`),
  UNIQUE INDEX `id_cedula_UNIQUE` (`idCedula` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `petshop`.`Productos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `petshop`.`Productos` (
  `idProducto` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  `precio` DECIMAL(9,0) NULL,
  `categoria` VARCHAR(45) NULL,
  PRIMARY KEY (`idProducto`),
  UNIQUE INDEX `idProducto_UNIQUE` (`idProducto` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `petshop`.`OrdenCompra`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `petshop`.`OrdenCompra` (
  `idOrdenCompra` INT NOT NULL,
  `cantidad` VARCHAR(45) NULL,
  `fecha` DATETIME NULL,
  `formaPago` VARCHAR(45) NULL,
  `montoTotalCompra` VARCHAR(45) NULL,
  `Cliente_idCedula` INT NOT NULL,
  `Productos_productoId` INT NOT NULL,
  PRIMARY KEY (`idOrdenCompra`),
  INDEX `fk_OrdenCompra_Cliente_idx` (`Cliente_idCedula` ASC) VISIBLE,
  INDEX `fk_OrdenCompra_Productos1_idx` (`Productos_productoId` ASC) VISIBLE,
  UNIQUE INDEX `idOrdenCompra_UNIQUE` (`idOrdenCompra` ASC) VISIBLE,
  CONSTRAINT `fk_OrdenCompra_Cliente`
    FOREIGN KEY (`Cliente_idCedula`)
    REFERENCES `petshop`.`Cliente` (`idCedula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_OrdenCompra_Productos1`
    FOREIGN KEY (`Productos_productoId`)
    REFERENCES `petshop`.`Productos` (`idProducto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `petshop`.`Facturas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `petshop`.`Facturas` (
  `idFecha` DATETIME(6) NOT NULL,
  `modoPago` VARCHAR(45) NULL,
  `nombreCliente` VARCHAR(45) NULL,
  `Facturascol` VARCHAR(45) NULL,
  `OrdenCompra_idOrdenCompra` INT NOT NULL,
  PRIMARY KEY (`idFecha`),
  INDEX `fk_Facturas_OrdenCompra1_idx` (`OrdenCompra_idOrdenCompra` ASC) VISIBLE,
  UNIQUE INDEX `idFecha_UNIQUE` (`idFecha` ASC) VISIBLE,
  CONSTRAINT `fk_Facturas_OrdenCompra1`
    FOREIGN KEY (`OrdenCompra_idOrdenCompra`)
    REFERENCES `petshop`.`OrdenCompra` (`idOrdenCompra`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `petshop`.`Domicilio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `petshop`.`Domicilio` (
  `idDomicilio` INT NOT NULL,
  `nombreCliente` VARCHAR(45) NULL,
  `apellido` VARCHAR(45) NULL,
  `correoEletronico` VARCHAR(45) NULL,
  `dirrecion` VARCHAR(45) NULL,
  `fechaEntrega` DATE NULL,
  `Facturas_idFecha` DATETIME(6) NULL,
  PRIMARY KEY (`idDomicilio`),
  UNIQUE INDEX `id_celular_UNIQUE` (`idDomicilio` ASC) VISIBLE,
  INDEX `fk_Domicilio_Facturas1_idx` (`Facturas_idFecha` ASC) VISIBLE,
  CONSTRAINT `fk_Domicilio_Facturas1`
    FOREIGN KEY (`Facturas_idFecha`)
    REFERENCES `petshop`.`Facturas` (`idFecha`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `petshop`.`Veterinario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `petshop`.`Veterinario` (
  `idVeterinario` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  `especialida` VARCHAR(45) NULL,
  `telefono` VARCHAR(45) NULL,
  PRIMARY KEY (`idVeterinario`),
  UNIQUE INDEX `idVeterinario_UNIQUE` (`idVeterinario` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `petshop`.`Cita`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `petshop`.`Cita` (
  `idCita` INT NOT NULL,
  `fecha` DATETIME NULL,
  `Cliente_idCedula` INT NOT NULL,
  PRIMARY KEY (`idCita`),
  INDEX `fk_Cita_Cliente1_idx` (`Cliente_idCedula` ASC) VISIBLE,
  CONSTRAINT `fk_Cita_Cliente1`
    FOREIGN KEY (`Cliente_idCedula`)
    REFERENCES `petshop`.`Cliente` (`idCedula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `petshop`.`Veterinario_has_Cita`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `petshop`.`Veterinario_has_Cita` (
  `Veterinario_idVeterinario` INT NOT NULL,
  `Cita_idCita` INT NOT NULL,
  PRIMARY KEY (`Veterinario_idVeterinario`, `Cita_idCita`),
  INDEX `fk_Veterinario_has_Cita_Cita1_idx` (`Cita_idCita` ASC) VISIBLE,
  INDEX `fk_Veterinario_has_Cita_Veterinario1_idx` (`Veterinario_idVeterinario` ASC) VISIBLE,
  CONSTRAINT `fk_Veterinario_has_Cita_Veterinario1`
    FOREIGN KEY (`Veterinario_idVeterinario`)
    REFERENCES `petshop`.`Veterinario` (`idVeterinario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Veterinario_has_Cita_Cita1`
    FOREIGN KEY (`Cita_idCita`)
    REFERENCES `petshop`.`Cita` (`idCita`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
